### ISSUE TITLE
Download instructions for Ubuntu cause warnings on apt update

### ISSUE THREAD

**Issue by lostfictions** [mono/website#544] opened 2020-12-19 01:00 UTC
Hi there, I'm on Ubuntu 20.04 and followed the instructions to install stable Mono on my system that are listed [here](https://www.mono-project.com/download/stable/#download-lin).

However, following these instructions:

```bash
sudo apt install gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
```

Produces the following warning:

> N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.mono-project.com/repo/ubuntu stable-focal InRelease' doesn't support architecture 'i386'

It's harmless, but it pops up on every run of `apt update`, which is somewhat annoying. If I change the entry in `/etc/apt/sources.list.d/mono-official-stable.list` to read

```
deb [arch=amd64] https://download.mono-project.....
```

instead of just

```
deb https://download.mono-project.....
```

The issue is resolved. So I'm wondering if it might be better to change the `echo` line above to something like this?

```bash
echo "deb [arch=`dpkg --print-architecture`] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
```

**Comment by akoeplinger** [comment] 2021-01-12 22:29
@directhex any idea why we get the i386 packages in this case? is this a new behavior in Ubuntu 20.04?

**Comment by akoeplinger** [comment] 2023-05-02 15:42
Couldn't reproduce this on Ubuntu 20.04, closing.

**Closed as completed by akoeplinger** 2023-05-02 15:42 UTC
